/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // poldevSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 poldevSidebar: [
   'readme',
   'Gestion du code source',
   'Intégration continue',
   'Environnements de développement, test et production',
   'Environnement de développement intégré',
   'Architecture des projets',
   'Tests unitaires et d\'intégration',
   'Qualité de code',
   'Documentation',
   'Sécurité',
   'FAQ',
   'RGAA',
   'Gestion des API',
],

};

export default sidebars;
