/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // poldevSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  polinfoSidebar: [

    // intro
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },

    // infra
    {
      type: 'category',
      collapsed: false,
      label: 'Politique d\'infrastructure',
      link: {type: 'doc', id: 'politique-infrastructure/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '01_politique-infrastructure/iaas',
        },
      ]
    },

    // support
    {
      type: 'category',
      label: 'Politique d\'informatique support',
      link: {type: 'doc', id: 'politique-support/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '02_politique-support',
        },
      ]
    },

    // dev
    {
      type: 'category',
      label: 'Politique de développement',
      link: {type: 'doc', id: 'politique-developpement/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '03_politique-developpement',
        },
      ]
    },


  ],

};

export default sidebars;
